import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Featured from "../components/Featured";
import PizzaCard from "../components/PizzaCard";
import PizzaList from "../components/PizzaList";
import axios from "axios";
export default function Home({pizzaList}) {
  return (
    <div className="">
      <Head>
        <title>Pizza shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <PizzaList pizzaList={pizzaList} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/product");

  return {
    props: {
      pizzaList: res.data,
    },
  };
};
